{
  gameClient: {
    observerServerIp: 'spectator-consumer.kr.lol.pvp.net',
    observerServerPort: 80,
    running: true,
    serverIp: '103.219.131.169',
    serverPort: 5184,
    visible: true
  },
  gameData: {
    gameId: 6734441277,
    gameName: '',
    isCustomGame: true,
    password: '',
    playerChampionSelections: [ [Object] ],
    queue: {
      allowablePremadeSizes: [],
      areFreeChampionsAllowed: true,
      assetMutator: '',
      category: 'Custom',
      championsRequiredToPlay: 0,
      description: '',
      detailedDescription: '',
      gameMode: 'CLASSIC',
      gameTypeConfig: [Object],
      id: -1,
      isRanked: false,
      isTeamBuilderManaged: false,
      lastToggledOffTime: 0,
      lastToggledOnTime: 0,
      mapId: 11,
      maximumParticipantListSize: 5,
      minLevel: 0,
      minimumParticipantListSize: 0,
      name: '',
      numPlayersPerTeam: 5,
      queueAvailability: 'Available',
      queueRewards: [Object],
      removalFromGameAllowed: false,
      removalFromGameDelayMinutes: 0,
      shortName: '',
      showPositionSelector: false,
      spectatorEnabled: false,
      type: 'PRACTICE_GAME'
    },
    spectatorsAllowed: false,
    teamOne: [ [Object] ],
    teamTwo: []
  },
  gameDodge: { dodgeIds: [], phase: 'None', state: 'Invalid' },
  map: {
    assets: {
      'champ-select-background-sound': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Shared/sound/music-cs-blindpick-default.ogg',
      'champ-select-flyout-background': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/img/champ-select-flyout-background.jpg',
      'champ-select-planning-intro': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/img/champ-select-planning-intro.jpg',
      'game-select-icon-active': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/img/game-select-icon-active.png',
      'game-select-icon-active-video': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/video/game-select-icon-active.webm',
      'game-select-icon-default': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/img/game-select-icon-default.png',
      'game-select-icon-disabled': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/img/game-select-icon-disabled.png',
      'game-select-icon-hover': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/img/game-select-icon-hover.png',
      'game-select-icon-intro-video': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/video/game-select-icon-intro.webm',
      'gameflow-background': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/img/gameflow-background.jpg',
      'gameflow-background-dark': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/img/gameflow-background-dark.jpg',
      'gameselect-button-hover-sound': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Shared/sound/sfx-gameselect-button-hover.ogg',
      'icon-defeat': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/img/icon-defeat.png',
      'icon-defeat-v2': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/img/icon-defeat-v2.png',
      'icon-defeat-video': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/video/icon-defeat.webm',
      'icon-empty': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/img/icon-empty.png',
      'icon-hover': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/img/icon-hover.png',
      'icon-leaver': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/img/icon-leaver.png',
      'icon-leaver-v2': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/img/icon-leaver-v2.png',
      'icon-loss-forgiven-v2': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/img/icon-loss-forgiven-v2.png',
      'icon-v2': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/img/icon-v2.png',
      'icon-victory': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/img/icon-victory.png',
      'icon-victory-video': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/video/icon-victory.webm',
      'map-north': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/img/map-north.png',
      'map-south': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/img/map-south.png',
      'music-inqueue-loop-sound': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/sound/music-inqueue-loop-summonersrift.ogg',
      'parties-background': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/img/parties-background.jpg',
      'postgame-ambience-loop-sound': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/sound/sfx-ambience-loop-summonersrift.ogg',
      'ready-check-background': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/img/ready-check-background.png',
      'ready-check-background-sound': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/sound/sfx-readycheck-sr-portal.ogg',
      'sfx-ambience-pregame-loop-sound': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/sound/sfx-ambience-loop-summonersrift.ogg',
      'social-icon-leaver': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/img/social-icon-leaver.png',
      'social-icon-victory': 'lol-game-data/assets/content/src/LeagueClient/GameModeAssets/Classic_SRU/img/social-icon-victory.png'
    },
    categorizedContentBundles: {},
    description: '가장 최근에 만들어졌으며 모두가 인정하는 전장은 소환사의 협곡입니다. 세 개의 공격로를 따라가 적의 약점을 찌르십시오. 아군과 협동하여 적 기지를 포위하고 적의 넥서스를 파괴하십시오!',
    gameMode: 'CLASSIC',
    gameModeName: '소환사의 협곡',
    gameModeShortName: '소환사의 협곡',
    gameMutator: '',
    id: 11,
    isRGM: false,
    mapStringId: 'SR',
    name: '소환사의 협곡',
    perPositionDisallowedSummonerSpells: {},
    perPositionRequiredSummonerSpells: {},
    platformId: '',
    platformName: '',
    properties: { suppressRunesMasteriesPerks: false }
  },
  phase: 'InProgress'
}